name: test-workflow

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-19.04
    steps:
      - name: checkout 
        uses: actions/checkout@master
        
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          version: 10.16.3
      - run: |
          npm i
          npm test